version: "2"

run:
  tests: true
  modules-download-mode: readonly

formatters:
  enable:
    - gofumpt
    - goimports

  settings:
    gofumpt:
      module-path: github.com/grffio/k8s-sts-scheduler

    goimports:
      local-prefixes:
        - github.com/grffio/k8s-sts-scheduler

  exclusions:
    generated: strict

linters:
  default: none

  enable:
    - bidichk
    - contextcheck
    - durationcheck
    - errcheck
    - errorlint
    - gocheckcompilerdirectives
    - gochecknoinits
    - gochecknoglobals
    - gocognit
    - gocritic
    - godoclint
    - gosec
    - govet
    - ineffassign
    - makezero
    - misspell
    - nilerr
    - nilnesserr
    - nolintlint
    - predeclared
    - reassign
    - recvcheck
    - revive
    - staticcheck
    - testifylint
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace

  settings:
    revive:
      enable-default-rules: true
      rules:
        - name: package-comments
          disabled: true

    govet:
      enable-all: true

    gocognit:
      min-complexity: 20

    nolintlint:
      require-explanation: true
      require-specific: true

  exclusions:
    generated: strict
    warn-unused: true