---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: app
spec:
  selector:
    matchLabels:
      app: app
  serviceName: "app"
  replicas: 3
  template:
    metadata:
      labels:
        app: app
        example.io/kind: "custom-scheduler"
    spec:
      schedulerName: sts-scheduler
      terminationGracePeriodSeconds: 3
      containers:
      - name: app
        image: busybox:1.36
        command: ["sleep", "infinity"]
